---
title: "Welcome"
---

## This website

This website collects the materials for a 2-day workshop on simulating power with R that [I'm](https://www.niklasjohannes.com/) giving at the [University of Vienna on May 4th and 5th 2022](https://vds-sosci.univie.ac.at/your-benefits/career-development-and-internationalisation/international-workshops/). Rather than dumping the materials in zip folder somewhere, I thought this format will be better for a) participants to revisit, b) those who might be interested in the content but couldn't make it. That's also the reason most of the materials are so annoyingly verbose: I wanted readers to be able to follow.

## Goal

The goal of the workshop is for you to (1) have an understanding of the philosophy behind using data to test claims, (2) get an intuition of how data generation processes work, (3) learn the technical skills in R to turn these processes into data, and (4) use these skills to simulate power for an informative study.

## Schedule

Below is the 2-day schedule. The times are more suggestions and not set in stone.

**Day 1**

| What?       | When?                    |
|-------------|--------------------------|
| 9:00-9:45   | Intro                    |
| 10:00-10:45 | What's power?            |
| 11:00-11:45 | Simulations in R         |
| 12:00-13:00 | Exercise 1               |
| 14:00-14:45 | Effect sizes             |
| 15:00-15:45 | Exercise 2               |
| 16:00-16:45 | Alpha, beta, sensitivity |
| 17:00-17:45 | Exercise 3               |
| 17:45-18:00 | Recap                    |


